# Fichier : codemagic.yaml

workflows:
  ios-app-sideload: # J'ai renommé le workflow pour plus de clarté
    name: iOS App Build (pour Sideloadly)
    environment:
      # On demande à Codemagic d'utiliser un Mac avec Xcode
      xcode: latest
      node: latest
    scripts:
      - name: Installer les dépendances
        script: | 
          npm install
      - name: Construire l'application web
        script: | 
          npm run build
      - name: Synchroniser avec le projet iOS natif
        script: | 
          npx cap sync ios
      # --- L'ÉTAPE DE SIGNATURE OFFICIELLE A ÉTÉ SUPPRIMÉE ---
      # - name: Configurer la signature du code (essentiel)
      #   script: | 
      #     xcode-project use-profiles
      - name: Construire le fichier IPA (Debug)
        script: | 
          # On ajoute --configuration Debug pour créer une version pour le sideloading
          xcode-project build-ipa --workspace "$CM_BUILD_DIR/ios/App/App.xcworkspace" --scheme App --configuration Debug
    artifacts:
      # On dit à Codemagic où trouver le fichier .ipa final
      - build/ios/ipa/*.ipa
