workflows:
  ios_unsigned_build:
    name: Crypto Pay Pro
    instance_type: mac_mini_m1 # Recommandé pour des builds plus rapides
    environment:
      vars:
        XCODE_SCHEME: "App"
        # XCODE_WORKSPACE: "App.xcworkspace"
    
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      
      - name: Build the web app
        script: |
          npm run build
      
      - name: Sync Capacitor with iOS
        script: |
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      
      - name: Build iOS unsigned .ipa
        script: |
          xcode-project build \
            --scheme "$XCODE_SCHEME" \
            --project "ios/$XCODE_SCHEME.xcodeproj" \
            --artifact-type ipa \
            --no-codesign
            
    artifacts:
      - $CM_BUILD_DIR/**/*.ipa