# codemagic.yaml - Solution finale avec .yarnrc.yml
workflows:
  ios-build:
    name: Build iOS App (Next.js + Capacitor)
    instance_type: mac_mini_m1
    environment:
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Installer les dépendances avec Yarn
        script: | 
          set -ex 
          # Grâce au fichier .yarnrc.yml, cette commande va maintenant fonctionner
          yarn install
          
      - name: Construire l'application web
        script: |
          set -ex
          yarn add @capacitor/cli@latest
          yarn build
          
      - name: Synchroniser avec le projet iOS natif
        script: |
          set -ex
          npx cap sync ios
          
      - name: Installer les dépendances iOS (Pods)
        script: |
          set -ex
          cd ios/App 
          pod install

      - name: Construire l'archive IPA
        script: |
          set -ex
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --export-options "ios/ExportOptions.plist"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Build/*.log