# codemagic.yaml
workflows:
  ios-build:
    name: Build iOS App
    instance_type: mac_mini_m1
    environment:
      xcode: latest # ou une version spécifique comme 15.3
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
        
      - name: Build iOS IPA
        script: | 
          set -e # Fait échouer le script si une commande échoue
          # Nettoyage du projet
          flutter clean
          # Lancement de la construction de l'IPA
          flutter build ipa --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Build/*.log