# codemagic.yaml - Approche finale pour contourner le bug de Yarn
workflows:
  ios-build:
    name: Build iOS App (Next.js + Capacitor)
    instance_type: mac_mini_m1
    environment:
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Installer les dépendances (méthode de contournement)
        script: | 
          set -ex 
          # On installe yarn en utilisant npm pour l'isoler de la configuration globale
          npm install -g yarn
          # On exécute l'installation
          yarn install
          
      - name: Construire l'application web
        script: |
          set -ex
          # On ajoute capacitor/cli pour s'assurer qu'il est disponible
          yarn add @capacitor/cli@latest
          yarn build
          
      - name: Synchroniser avec le projet iOS natif
        script: |
          set -ex
          # On utilise npx pour exécuter la commande capacitor
          npx cap sync ios
          
      - name: Installer les dépendances iOS (Pods)
        script: |
          set -ex
          cd ios/App 
          pod install

      - name: Construire l'archive IPA
        script: |
          set -ex
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --export-options "ios/ExportOptions.plist"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Logs/Build/*.log