# codemagic.yaml
workflows:
  ios-build:
    name: Build iOS App
    instance_type: mac_mini_m1
    
    # C'est la ligne la plus importante. 
    # Elle dit à Codemagic d'entrer dans ce dossier avant de lancer les commandes.
    working_directory: crypto-app-info-main 
    
    environment:
      xcode: latest
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter pub get
        
      - name: Build iOS IPA
        script: | 
          set -e
          flutter build ipa --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa